---
title: "AFT_frequentist_adjustedByAllvars"
author: "Lina M. Ruiz G."
date: "5/26/2022"
output: html_document
---

```{r}
library(dplyr)
library(survival)
library(dplyr)
library(survminer)
#library(naniar)
library(MASS)
library(flexsurv)
library(stargazer)
library(pander)
```

```{r}
data <- read.csv("/home/lina/Documents/unCoVer/uncoverP1LoS/dataBases/dataBaseAnalysis13.csv")
data<-data %>% filter( tRD <100)
data$AgeG <- case_when(data$AgeYears > 1 & data$AgeYears <= 25 ~ "1",
                       data$AgeYears > 25 & data$AgeYears <= 50 ~ "2",
                         data$AgeYears > 50 & data$AgeYears <= 75 ~ "3",
                         data$AgeYears > 75 & data$AgeYears <= 100 ~ "4")
data$outcome <- rep(1,nrow(data))
data$outcomeRD <- case_when(data$X1BedPathway == 1 ~ "R",
                            data$X1BedPathway == 2 ~ "D",
                            data$X1BedPathway == 3 ~ "R",
                            data$X1BedPathway == 4 ~ "D",
                            data$X1BedPathway == 5 ~ "R",
                            data$X1BedPathway == 6 ~ "R",
                            data$X1BedPathway == 7 ~ "D",
                            data$X1BedPathway == 8 ~ "R",
                            data$X1BedPathway == 9 ~ "R",
                            data$X1BedPathway == 10 ~ "D",
                            data$X1BedPathway == 11 ~ "D",
                            data$X1BedPathway == 12 ~ "D")

data$X1BedPathway <- as.factor(data$X1BedPathway)
data$PeaksValleys2 <- as.factor(data$PeaksValleys2)
data$Waves <- as.factor(data$Waves)
```

```{r}
#Models data

# data model H -> RD
data_H_RD<-data %>% filter(X2BedPathway == 1)
data_H_RD$times<-data_H_RD$tRD

data_H_RD2 <- data_H_RD %>% 
  filter( !is.na(times)& 
            !is.na(Waves)& 
            !is.na(PeaksValleys2))

data_H_RD3 <- data_H_RD2 |> 
  dplyr::select(times, outcome,outcomeRD,AgeG,Gender, Waves, PeaksValleys2, Vaccination) 

data_H_RD4 <- na.omit(data_H_RD)


# data model ICU -> RD
data_ICU_RD<-data %>% filter(X2BedPathway == 2)
data_ICU_RD$times<-data_ICU_RD$tRD
```

```{r}
#Model
aft <- with(data_H_RD,Surv(data_H_RD$times, data_H_RD$outcome==1))

gmma.aft_H_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_H_RD, dist = "gamma")

exp.aft_H_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_H_RD, dist = "exp")

llogis.aft_H_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_H_RD, dist = "llogis")

lnorm.aft_H_RD <- flexsurvreg(aft ~  outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination,  data=data_H_RD, dist = "lnorm")

weibull.aft_H_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_H_RD, dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"), AIC = c( gmma.aft_H_RD$AIC, exp.aft_H_RD$AIC, llogis.aft_H_RD$AIC, lnorm.aft_H_RD$AIC, weibull.aft_H_RD$AIC))
pander(df,style = "simple", caption = "H-RD")
```


```{r}
lnorm.aft_H_RD
```

```{r}
aft <- with(data_H_RD4,Surv(data_H_RD4$times, data_H_RD4$outcome==1))
m1<-survreg(aft ~  outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_H_RD4, dist = "lognormal")
m1
```

```{r}
stepAIC1<- stepAIC(m1, direction="both", criterion='AIC')
```

```{r}
summary(stepAIC1)
```


```{r}
library(corrplot)
M <- cor(data_H_RD)
corrplot(M, method="circle")
```
```{r}
install.packages("GGally")
library(GGally)
data_H_RD2 |> 
  dplyr::select(outcomeRD,AgeG,Gender, Waves, PeaksValleys2, Vaccination) |>  ggpairs()
```





```{r}
predict(lnorm.aft_H_RD) |> summary()

```

```{r}
predict(lnorm.aft_H_RD, newdata = filter(data_H_RD,AgeG=="2"))|> summary()
```

```{r}
predict(lnorm.aft_H_RD, newdata = filter(data_H_RD,AgeG=="2"))|> summary()
```

```{r}
#Model
aft<- with(data_ICU_RD,  Surv (data_ICU_RD$times,data_ICU_RD$outcome==1))

gmma.aft_ICU_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_ICU_RD, dist = "gamma")

exp.aft_ICU_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_ICU_RD, dist = "exp")

llogis.aft_ICU_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_ICU_RD, dist = "llogis")

lnorm.aft_ICU_RD <- flexsurvreg(aft ~  outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination,  data=data_ICU_RD, dist = "lnorm")

weibull.aft_ICU_RD <- flexsurvreg(aft ~ outcomeRD + AgeG + Gender + Waves + PeaksValleys2 + Vaccination, data=data_ICU_RD, dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft_H_RD$AIC, exp.aft_H_RD$AIC, llogis.aft_H_RD$AIC, lnorm.aft_H_RD$AIC, weibull.aft_H_RD$AIC))
pander(df,style = "simple", caption = "ICU-RD")
```




```{r}
lnorm.aft_ICU_RD
```

