---
title: "AFTs_frequentist"
author: "Lina M. Ruiz G."
date: "3/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(survival)
library(dplyr)
library(survminer)
library(naniar)
library(MASS)
library(flexsurv)
library(tidyverse)
library(stargazer)
library(pander)
```

# data

```{r}
#data <- read.csv("/home/lina/Documents/UnCover/uncoverP1LoS/dataBases/dataBaseAnalysis12.csv")
data <- read.csv("/home/lina/Documents/UnCover/uncoverP1LoS/dataBases/dataBaseAnalysis13.csv")
data<-data %>% filter( tRD <100)
data$AgeG <- case_when(data$AgeYears > 1 & data$AgeYears <= 50 ~ "1",
                         data$AgeYears > 50 & data$AgeYears <= 64 ~ "2",
                         data$AgeYears > 64 & data$AgeYears <= 74 ~ "3",
                         data$AgeYears > 74 ~ "4")
data$outcome <- rep(1,nrow(data))
data$Waves<- as.factor(data$Waves)
```




```{r}
#Models data

# data model H -> RD
data_H_RD<-data %>% filter(X2BedPathway == 1)
data_H_RD$times<-data_H_RD$tRD

# data model H -> ICU BP3
data_H_ICUf<-data %>% filter(X2BedPathway == 3)
data_H_ICUf$times<-data_H_ICUf$tICUf
# data model ICU-> RD BP3
data_ICUf_RD<-data %>% filter(X2BedPathway == 3)
data_ICUf_RD$times<-data_ICUf_RD$tRD-data_ICUf_RD$tICUf
# data model  BP3
data_BP3<-data %>% filter(X2BedPathway == 3)
data_BP3$times<-data_BP3$tRD

# data model H -> ICU BP5
data_H_ICUt<-data %>% filter(X2BedPathway == 5)
data_H_ICUt$times<-data_H_ICUt$tICUt
# data model ICU-> H2 BP5
data_ICU_H2<-data %>% filter(X2BedPathway == 5)
data_ICU_H2$times<-data_ICU_H2$tH2-data_ICU_H2$tICUt
# data model H2-> RD BP5
data_H2_RD<-data %>% filter(X2BedPathway == 5)
data_H2_RD$times<-data_H2_RD$tRD-data_H2_RD$tH2
# data model  BP5
data_BP5<-data %>% filter(X2BedPathway == 5)
data_BP5$times<-data_BP5$tRD

# data model ICU -> RD
data_ICU_RD<-data %>% filter(X2BedPathway == 2)
data_ICU_RD$times<-data_ICU_RD$tRD

# data model ICU -> H BP4
data_ICU_Hf<-data %>% filter(X2BedPathway == 4)
data_ICU_Hf$times<-data_ICU_Hf$tHf
# data model H -> RD BP4
data_Hf_RD<-data %>% filter(X2BedPathway == 4)
data_Hf_RD$times<-data_Hf_RD$tRD-data_Hf_RD$tHf
# data model  BP4
data_BP4<-data %>% filter(X2BedPathway == 4)
data_BP4$times<-data_BP4$tRD

# data model ICU -> H BP6
data_ICU_Ht<-data %>% filter(X2BedPathway == 6)
data_ICU_Ht$times<-data_ICU_Ht$tHt
# data model H-> ICU2 BP6
data_H_ICU2<-data %>% filter(X2BedPathway == 6)
data_H_ICU2$times<-data_H_ICU2$tICU2-data_H_ICU2$tHt
# data model ICU2-> RD BP6
data_ICU2_RD<-data %>% filter(X2BedPathway == 6)
data_ICU2_RD$times<-data_ICU2_RD$tRD-data_ICU2_RD$tICU2
# data model BP6
data_BP6<-data %>% filter(X2BedPathway == 6)
data_BP6$times<-data_BP6$tRD
```

```{r}
table(data_H_RD$Waves)
table(data_ICU_RD$Waves)
nrow(data_H_RD)
nrow(data_ICU_RD)
```

# H - RD BP1


```{r}
#Model
aft_H_RD<- with(data_H_RD,  Surv (data_H_RD$times,data_H_RD$outcome==1))

gmma.aft_H_RD <- flexsurvreg(aft_H_RD  ~  Waves , data=data_H_RD,
                         dist = "gamma")
exp.aft_H_RD <- flexsurvreg(aft_H_RD  ~ Waves, data=data_H_RD,
                         dist = "exp")
llogis.aft_H_RD <- flexsurvreg(aft_H_RD  ~ Waves, data=data_H_RD,
                         dist = "llogis")
lnorm.aft_H_RD <- flexsurvreg(aft_H_RD  ~  Waves , data=data_H_RD,
                         dist = "lnorm")
weibull.aft_H_RD <- flexsurvreg(aft_H_RD  ~ Waves, data=data_H_RD,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft_H_RD$AIC, exp.aft_H_RD$AIC, llogis.aft_H_RD$AIC, lnorm.aft_H_RD$AIC, weibull.aft_H_RD$AIC))
pander(df,style = "simple", caption = "H-RD")
```


```{r}
#data13
lnorm.aft_H_RD
```

```{r}
#data13
lnorm.aft_H_RD
```


```{r}
flexsurvreg(aft_H_RD  ~ Waves + sdlog(Waves), data=data_H_RD,
                         dist = "lnorm")
```

```{r}
# with the 2 wave as basal group: this is to see if the form of the time distributions changes when the basal group changes

data_H_RD<-data_H_RD %>% filter( Waves != "1")
aft_H_RD<- with(data_H_RD,  Surv (data_H_RD$times,data_H_RD$outcome==1))
flexsurvreg(aft_H_RD  ~ Waves + sdlog(Waves), data=data_H_RD,
                         dist = "lnorm")
```

```{r}
# with the 2 wave as basal group: this is to see if the form of the time distributions changes when the basal group changes

data_H_RD<-data_H_RD %>% filter( Waves != "2")
aft_H_RD<- with(data_H_RD,  Surv (data_H_RD$times,data_H_RD$outcome==1))
flexsurvreg(aft_H_RD  ~ Waves + sdlog(Waves), data=data_H_RD,
                         dist = "lnorm")
```
```{r}
#CONCLUTION:  It does not matter who is the basal group the time distribution built for each category is almost the same although the estimates change according to the model-basal group: to see this review 7. descriptiveAnalysisDataLoS.nb/Estimatios from the AFTf results / For the whole data outcome R&D
```

# H - ICUf BP3

```{r}
#Model
aft<- with(data_H_ICUf,  Surv (data_H_ICUf$times,data_H_ICUf$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves, data=data_H_ICUf,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft  ~ Waves , data=data_H_ICUf,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves , data=data_H_ICUf,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~ Waves , data=data_H_ICUf,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~ Waves , data=data_H_ICUf,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUf")
```

```{r}
flexsurvreg(aft  ~ Waves + shape(Waves), data=data_H_ICUf, dist = "gamma")
```

```{r}
#data13
flexsurvreg(aft  ~ Waves , data=data_H_ICUf, dist = "lnorm")
```
```{r}
flexsurvreg(aft  ~ Waves , data=data_H_ICUf, dist = "lnorm")
```





# ICUf - RD BP3

```{r}
#Model
aft<- with(data_ICUf_RD,  Surv (data_ICUf_RD$times,data_ICUf_RD$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves, data=data_ICUf_RD,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft  ~ Waves, data=data_ICUf_RD,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves , data=data_ICUf_RD,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~ Waves , data=data_ICUf_RD,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~ Waves , data=data_ICUf_RD,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUf")
```
```{r}
#data13
lnorm.aft
```

```{r}
lnorm.aft
```


```{r}
flexsurvreg(aft  ~ AgeG + sdlog(AgeG), data=data_ICU_RD, dist = "lnorm")
```

#  BP3

```{r}
#Model
aft<- with(data_BP3,  Surv (data_BP3$times,data_BP3$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves , data=data_BP3,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft  ~ Waves , data=data_BP3,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves , data=data_BP3,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~ Waves, data=data_BP3,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~ Waves, data=data_BP3,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUt")
```

```{r}
#data13
lnorm.aft
```

```{r}
lnorm.aft
```



# ICU - RD BP2

```{r}
#Model
aft<- with(data_ICU_RD,  Surv (data_ICU_RD$times,data_ICU_RD$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves, data=data_ICU_RD,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft ~ Waves, data=data_ICU_RD,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves, data=data_ICU_RD,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~ Waves, data=data_ICU_RD,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~  Waves, data=data_ICU_RD,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUt")
```

```{r}
#data13
lnorm.aft
```

```{r}
lnorm.aft
```

```{r}
flexsurvreg(aft  ~ AgeG + sdlog(AgeG), data=data_ICU_RD, dist = "lnorm")
```

# ICU - Hf BP4
```{r}
#Model
aft<- with(data_ICU_Hf,  Surv (data_ICU_Hf$times,data_ICU_Hf$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves, data=data_ICU_Hf,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft  ~ Waves, data=data_ICU_Hf,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves, data=data_ICU_Hf,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~  Waves, data=data_ICU_Hf,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~ Waves, data=data_ICU_Hf,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUt")
```

```{r}
#data13
lnorm.aft
```

```{r}
lnorm.aft
```

# Hf - RD BP4
```{r}
#Model
aft<- with(data_Hf_RD,  Surv (data_Hf_RD$times,data_Hf_RD$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves, data=data_Hf_RD,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft  ~ Waves, data=data_Hf_RD,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves, data=data_Hf_RD,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~ Waves, data=data_Hf_RD,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~  Waves, data=data_Hf_RD,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUt")
```

```{r}
#data13
lnorm.aft
```

```{r}
lnorm.aft
```




#  BP4
```{r}
#Model
aft<- with(data_BP4,  Surv (data_BP4$times,data_BP4$outcome==1))

gmma.aft <- flexsurvreg(aft ~ Waves, data=data_BP4,
                         dist = "gamma")
exp.aft <- flexsurvreg(aft  ~  Waves, data=data_BP4,
                         dist = "exp")
llogis.aft <- flexsurvreg(aft  ~ Waves, data=data_BP4,
                         dist = "llogis")
lnorm.aft <- flexsurvreg(aft  ~ Waves, data=data_BP4,
                         dist = "lnorm")
weibull.aft <- flexsurvreg(aft  ~ Waves, data=data_BP4,
                         dist = "weibull")

df<-data.frame(Model = c("Gamma", "Exponential","LogLogistic","lognormal","weibull"),AIC = c( gmma.aft$AIC, exp.aft$AIC, llogis.aft$AIC, lnorm.aft$AIC, weibull.aft$AIC))
pander(df,style = "simple", caption = "H-ICUt")
```

```{r}
#data13
lnorm.aft
```

```{r}
lnorm.aft
```




